#!/bin/sh
#based on https://github.com/richo/git_template/blob/master/hooks/ctags
set -e
PATH="/usr/local/bin:$PATH"

mkdir .git/tags_lock 2>/dev/null || exit 0
trap "rmdir .git/tags_lock; rm -f .git/tags.$$" EXIT

echo "Running ctags on repository"
ctags --tag-relative -R -f .git/tags.$$ --exclude=.git --languages=-sql
mv .git/tags.$$ .git/tags
